name: 'Get & cache dependencies'
description: 'Get the deps (via npm) and cache them'
inputs:
  caching:
    description: 'Whether to cache deps or not'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: | 
        npm ci
        echo "::set-output name=cache::'${{ inputs.caching }}'"
      # composite actionを作る際は、shellを設定する必要がある。
      shell: bash