name: Output information
on: workflow_dispatch
jobs:
  info:
   runs-on: ubuntu-latest
   steps:
     # @see https://docs.github.com/ja/actions/learn-github-actions/contexts
     - name: Output Github context
       run: echo "${{ toJSON(gihthub) }}"